name: upload github code to kaggle
run-name: ${{ github.actor }} is uploading github code to kaggle

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "upload"
  upload:
    # Only triggers if string "upload to kaggle" is found in the commit message
    if: "contains(github.event.commits[0].message, 'upload to kaggle')"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Upload github code to kaggle
        # uses: jaimevalero/push-kaggle-dataset@v3 # This is the action
        uses: Nov05/action-push-kaggle-dataset@v1
        env:
          # Do not leak your credentials.
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

        with:
          ## Default is "{KAGGLE_USERNAME}/{GITHUB_REPO_NAME}" Where KAGGLE_USERNAME is a secret
          # id:  ${{ secrets.KAGGLE_USERNAME }}/kaggle--feedback-prize-ell
          title: "Code for Feedback Prize English Language Learning"
          subtitle: "Synced using Github actions"
          description: "## We generate features with Deberta V3 models using a sklearn transformer"
          files: |
            *.py
            *.md
            *.yml 
            trainers
            .gitignore
            .gitattributes
          is_public: true